version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev --features=scripts,upload-scripts
    ports:
      - 8080:8080
